name: CD
on:
  # Runs on all push events on main.
  push:
    branches: [ main ]

permissions:
  # Can only read the source code.
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          application-name: squelette

  semver:
    name: Semver
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/semver
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

#  deploy:
#    name: Deploy
#    needs: semver
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy
#        with:
#          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
#          service-account-key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#          project-id: ${{ secrets.GCP_PROJECT_ID }}
#          region: ${{ secrets.GCP_REGION }}
#          repository: ${{ secrets.GCP_REPOSITORY_NAME }}
#          service: ${{ secrets.GCP_SERVICE_NAME }}
